export interface StudentViewModel {
    id: string;
    studentEnrollmentId: string;
    firstName: string;
    lastName: string;
    gender: number;
    age: number;
    grandGatherName: string;
    fatherName: string;
    motherName: string;
    parentContactNumber: string;
    parentEmail?: string;
    classRoomId: string;
    classRoomName: string;
    sectionId: string
    sectionName: string;
    displayName?: string;
    address: string;
    dateOfBirthNp: string;
    dateOfBirthEn: string;
    provinceId: number;
    districtId: number;
    municipalityId: number;
    municipalityName: string;
    wardNo: number;
    classSectionId?: string;
    rollNumber?: number;
    isBusRequired?: boolean;
    isActive: boolean;
    enrollmentStatus?: number;
    enrollmentStatusName?: string;
    statusDate?: string;
    statusRemarks?: string;
}
